version: '3.3'

services:

  portainer:
    # TODO: pin down a specific version of portainer
    image: portainer/portainer
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - server

  server:
    build: ..
    image: max2wms/hologram-mart
    ports:
      - "63145:63145"
    depends_on:
      - db

  db:
    # TODO: pin down a specific version of mongo
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "mongo_db:/data/db"
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet

volumes:
  mongo_db: