version: '3.3'

services:

  viz:
    image: dockersamples/visualizer
    ports:
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - hologram_mart
    depends_on:
      - db
      - server
      - portainer

  portainer:
    image: portainer/portainer
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - hologram_mart
    depends_on:
      - db
      - server
      - viz

  server:
    image: max2wms/hologram-mart
    ports:
      - '63145:63145'
    networks:
      - hologram_mart
    depends_on:
      - db

  db:
    image: 'mongo'
    ports:
      - '27017:27017'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - 'mongo_db:/data/db'
    networks:
      - hologram_mart
    command: mongod --smallfiles --logpath=/dev/null

volumes:
  mongo_db:

networks:
  hologram_mart:
