version: '3.3'

services:

  portainer:
    # TODO: pin down a specific version of portainer
    container_name: portainer
    image: portainer/portainer
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - hologram_mart
    depends_on:
      - db
      - server

  server:
    container_name: server
    build: ..
    image: max2wms/hologram-mart
    ports:
      - "80:63145"
    networks:
      - hologram_mart
    depends_on:
      - db

  db:
    # TODO: pin down a specific version of mongo
    container_name: db
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "mongo_db:/data/db"
    ports:
      - "27017:27017"
    networks:
      - hologram_mart
    command: mongod --logpath=/dev/null # --quiet

volumes:
  mongo_db:

networks:
  hologram_mart: